/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package System;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import library.assistant.database.DatabaseHandler;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author thead
 */
public class user_reply extends javax.swing.JFrame {

    /**
     * Creates new form grievance_details
     */
    public user_reply() {
        initComponents();
        
        
               DatabaseHandler databaseHandler= new DatabaseHandler();   
       
  String descrip="";
 ResultSet rs=null;
  String query="SELECT * FROM REPLY_TABLE";
  try{
                    rs=databaseHandler.execQuery(query);
                     jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                      descrip =jTable1.getModel().getValueAt(0, 5).toString();
                        jLabel2.setText(jTable1.getModel().getValueAt(0, 0).toString());
                     jTable1.removeColumn(jTable1.getColumnModel().getColumn(5));
                     rs.close();    }
   catch (SQLException e){
            e.printStackTrace();
        }
  
   jTextArea2.setText(descrip);
  
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel2 = new keeptoo.KGradientPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 153, 255));
        kGradientPanel1.setkGradientFocus(100);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(23, 35, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 42)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Reply");

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/resourses/quit.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(100, 100, 100));
        jTextField3.setText("Enter Your ID");
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(23, 35, 51));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Reply :");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jLabel15.setBackground(new java.awt.Color(23, 35, 51));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Description :");

        jRadioButton1.setBackground(new java.awt.Color(0, 153, 255));
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Complaint against Authorites");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(1064, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3))
                        .addComponent(jLabel2)))
                .addGap(0, 80, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1096, 706));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     
               
                    
      String grievance_id="";
      
     grievance_id =jTable1.getModel().getValueAt(0, 0).toString();
                    
                    
      String date="";
      String subject="";
      String name="";
      String id="";
      String descrip="";
      String status="";
     DatabaseHandler databaseHandler= new DatabaseHandler();     
        //insert back in grievance // delete from reply with no update
        
                       String query="SELECT * FROM REPLY_TABLE  where REPLY_TABLE.GRIEVANCE_ID='"+grievance_id+"'";
 ResultSet resobj=null;
        try {  
       resobj =databaseHandler.execQuery(query);
           
        while(resobj.next()){
                
                grievance_id = resobj.getString(1);
                date = resobj.getString(2);
                subject = resobj.getString(3);
                name = resobj.getString(4);
                id = resobj.getString(5);
                descrip = resobj.getString(6);
                status = resobj.getString(7);
        }
        }

        catch (SQLException e){
            e.printStackTrace();
        }
        
        
          query="INSERT INTO RESPONSE  VALUES("
                + "'" + grievance_id + "',"
                + "'" + date + "',"
                + "'" + subject + "',"
                + "'" + name + "',"
                + "'" + id + "',"
                + "'" + descrip + "',"
                + "'" + status + "'"
               + ")";
     databaseHandler.execAction(query);
        
        
        query= "DELETE FROM REPLY_TABLE WHERE REPLY_TABLE.GRIEVANCE_ID ='"+grievance_id+"'"; 
     databaseHandler.execAction(query);
       
        
        this.hide();
        user_my back=new user_my();
        back.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
        DatabaseHandler databaseHandler= new DatabaseHandler();          
       String  temp=jTextField3.getText().trim();
        
       String query="SELECT * FROM PUBLIC_LOGIN where PUBLIC_LOGIN.ID='"+temp+"'";
        
        
        
         try {

                     ResultSet resobj=databaseHandler.execQuery(query);
            if(resobj.next()){
                
                
                
                ////////////////////////////////////////////////////////////
                
                
            
        
        String grievance_id="";
      
     grievance_id =jTable1.getModel().getValueAt(0, 0).toString();
                    
                    
      String date="";
      String subject="";
      String name="";
      String id="";
      String descrip="";
      String status="";
   
        //insert back in grievance // delete from reply with no update
        
                        query="SELECT * FROM REPLY_TABLE  where REPLY_TABLE.GRIEVANCE_ID='"+grievance_id+"'";
  resobj=null;
        try {  
       resobj =databaseHandler.execQuery(query);
           
        while(resobj.next()){
                
                grievance_id = resobj.getString(1);
                date = resobj.getString(2);
                subject = resobj.getString(3);
                name = resobj.getString(4);
                id = resobj.getString(5);
                descrip = resobj.getString(6);
                status = resobj.getString(7);
                        status="Opened";
        }
        
   
         
        
        }

        catch (SQLException e){
            e.printStackTrace();
        }     
        
         query= "DELETE FROM REPLY_TABLE WHERE REPLY_TABLE.GRIEVANCE_ID ='"+grievance_id+"'"; 
     databaseHandler.execAction(query);
        
         
        status="Opened";
        
            
          query="INSERT INTO RESPONSE  VALUES("
                + "'" + grievance_id + "',"
                + "'" + date + "',"
                + "'" + subject + "',"
                + "'" + name + "',"
                + "'" + id + "',"
                + "'" + descrip + "',"
                + "'" + status + "'"
               + ")";
     databaseHandler.execAction(query);
        
        
          //   change date ,name ,id
         SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
	Date datex = new Date();
	date=formatter.format(datex);
        
        
        id=jTextField3.getText().trim();
        
       query="SELECT * FROM PUBLIC_LOGIN where PUBLIC_LOGIN.ID='"+id+"'";
                 resobj =databaseHandler.execQuery(query);
           
        try{
            while(resobj.next()){
                
                name = resobj.getString(1);
               
        }
        }
        
          catch (SQLException e){
            e.printStackTrace();
        }
        descrip=jTextArea1.getText().trim();
        
            
      grievance_id=grievance_id.substring(0, 8);
     grievance_id=grievance_id.concat(":Re");
     
     
          query="INSERT INTO GRIEVANCE  VALUES("
                + "'" + grievance_id + "',"
                + "'" + date + "',"
                + "'" + subject + "',"
                + "'" + name + "',"
                + "'" + id + "',"
                + "'" + descrip + "',"
                + "'" + status + "'"
               + ")";
     databaseHandler.execAction(query);
     
              if(jRadioButton1.isEnabled()==true){
                  query="INSERT INTO AGAINST VALUES("
                + "'" + grievance_id + "',"
                + "'" + date + "',"
                + "'" + subject + "',"
                + "'" + name + "',"
                + "'" + id + "',"
                + "'" + descrip + "',"
                + "'" + status + "'"
               + ")";
              
              databaseHandler.execAction(query);
              }
        
         JOptionPane.showMessageDialog(this,"Replied to the Response Successfully");
        
          this.hide();
        user_my back=new user_my();
        back.setVisible(true);     
                
                
                
                
                
                
                
                
                
                
            /////////////////////////////////////////////////////////////////////    
                
            }
            
            else
            {  JOptionPane.showMessageDialog(this,"Wrong ID");}
        
         }
          catch (SQLException e){
            e.printStackTrace();
        }     
        
        
       

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        jTextField3.setText("");
        jTextField3.setForeground(new java.awt.Color(70, 70, 70));        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3MouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_reply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_reply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_reply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_reply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_reply().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    // End of variables declaration//GEN-END:variables
 

}

